### PR TITLE
ownCloud log parsing

### PR DESCRIPTION
**Pull request by ageis**
There are two types of messages in the ownCloud log, and this handles them both.

### CODE REVIEW

**Comment by conorsch** [comment]
The log format is JSON, which is already structured by field. Use the [json filter](https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html) to map the JSON to a logstash event. That way we'll have fewer patterns to maintain.

**Comment by ageis** [comment]
@conorsch Thanks for the tip.

**Comment by ageis** [comment]
@conorsch done

**Comment by conorsch** [comment]
Dang, I wish we had more logs in JSON!

**Pull request merged**
