### PR TITLE
Alerts for high load average and memory usage

### PR DESCRIPTION
**Pull request by ageis**
This should ideally allow you to obliviate `41-daily-metrics.conf`.

### CODE REVIEW

**Comment by ageis** [comment]
If you require host-specific thresholds (say, you have one box that regularly runs at mem > 95%, or load > 2.0) I think that might be better to do in Riemann. For inspiration see:

https://gist.github.com/rantav/8296978#file-riemann-config-L12
https://github.com/pyr/riemann-extra/blob/master/src/org/spootnik/riemann/thresholds.clj

**Comment by ageis** [comment]
That said, you could also do it this way:

```
  if [type] == "system" {
    ruby {
      code => "
        event['load_threshold'] = 1.0
        event['load_threshold'] = 2.0 if event['beat']['hostname'] == 'highloadmachine.com'
        event['mem_threshold'] = 0.90
        event['mem_threshold'] = 0.98 if event['beat']['hostname'] == 'memoryintensivemachine.net'
        event['mem_threshold_percent'] = event['mem_threshold'] * 100.to_f
        event['mem_threshold_str'] = event['mem_threshold_percent'].to_i.to_s
      "
    }
    if [load][load15] >= [load_threshold] {
      mutate {
        add_tag => "slack_alert"
        add_tag => "load_warning"
        add_field => { "original_message" => "%{message}" }
        replace => { "message" => "Load average is above %{[load_threshold]}" }
      }
    }
    if [mem][actual_used_p] >= [mem_threshold] {
      mutate {
        add_tag => "slack_alert"
        add_tag => "memory_warning"
        add_field => { "original_message" => "%{message}" }
        replace => { "message" => "Memory usage is above %{[mem_threshold_str]}%" }
      }
    }

```

**Comment by ageis** [comment]
Latest commit puts the default thresholds into variables and allows custom per-host settings via `host_vars/all`.

**Comment by conorsch** [comment]
Hey, this is sharp! Can you update the new vars to contain the `elk_` prefix? That'd be consistent with all the vars in the role. We're interested in breaking out all the functionality for the various components into separate roles, but this role would still be useful as a wrapper for a turnkey deployment on a single host, if the number of clients is not huge.

**Comment by ageis** [comment]
@conorsch Ok, done that. Also decided 3.0 is a more sensible default load average alert threshold, based on my own usage of this in production (2.0 was noisy on a few machines). Since load is relative to cores, it will vary from system to system. Assuming most of your droplets have at least 2 vCPUs, 3.0 should be roughly when you definitely want to start investigating what's eating cycles. But that variation is why we have custom per-host settings anyway.

**Pull request closed without merging**
